parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: '3306'
    database_name: agiletourreg
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: es
    secret: 883aa3b1d562a19a8b0ad414b4a3296996c05496
